### ISSUE TITLE
Passing around exc_info tuples sucks

### ISSUE THREAD

**Issue by radix** [python-effect/effect#24]
Sadly, Twisted's Failure is not a third-party module, or I'd have used it from the beginning.

There is the effect.twisted.exc_info_to_failure utility function, which helps marginally for Twisted users, but it's still not great. And for anyone else, exc_info tuples are downright unwieldy -- you have to import the `traceback` module and _apply_ the tuple to `traceback.print_exception` -- so it can't simply be added as a callback, without a lambda wrapping it like `lambda exc_info: traceback.print_exception(*exc_info)`. 

And that's just to print it -- if you want to log it with the stdlib `logging` module, you have to ... actually, I don't even know how you pass a traceback to the `logging` module, after briefly looking at its documentation. So, clearly, this is a user experience that could be vastly improved.

I don't know what the solution is. Maybe Failure could be factored out to its own third-party library, but that will probably be a lot of work. Whatever it is, I want errors from Effects to be trivial to print, log, and handle as structured data.

**Comment by radix** [comment]
Turns out you can pass an `exc_info` tuple to the stdlib `logging` library -- but not to the `exception` method, amusingly enough. you just pass the tuple as a keyword argument `exc_info`.

**Comment by radix** [comment]
@rbtcollins suggests an API like this:

def handle(thunk):
    try:
        result = thunk()
    except:
        # got error
    else:
        # got result
eff.bind(handle)


This would allow us to avoid ever leaking exc_info into user code (at least when it comes to the Effect API; the performer API is another thing altogether).

**Comment by rbtcollins** [comment]
Yeah, haskells no-brackets makes binding much more aesthetically pleasing, but I think this would be quite ok.
