### ISSUE TITLE
Figure out a way to not need to instantiate Effect() explicitly everywhere

### ISSUE THREAD

**Issue by radix** [python-effect/effect#37]
This siren song leads me down a dangerous path.

Instantiating Effect() to wrap around intents everywhere is tedious and makes things harder to explain. It'd be nice to not need to do that.

**Comment by radix** [comment]
Random ideas:

- Intent base class with `on` method returning `Effect(self, callbacks=[cb, eb])`, or perhaps an `on` toplevel function which returns `Effect(self, callbacks=[cb, eb])`. The other part would be a special case in perform() so that it can deal with an intent passed directly without being wrapped in an effect: ugly.

Alternatively `Effect` could be removed entirely. How would we deal with callbacks in that case? Well, they could be managed by an `Intent` base class, which would have an `on` method that would return a copy of self + callbacks. but _then_ it becomes harder to compare intents in tests (like, "assert that the intent WITHOUT CALLBACKS has this data...").

I will stew on this stuff for a while.

**Comment by radix** [comment]
I'm just gonna close this, I don't think it's going to work out.

**Comment by RonnyPfannschmidt** [comment]
i think there actually is a way to do it

for effects that are implemented in terms of other effects, in case the intermediates shouldnt have own handling, it could be fine to just pass on the exceptions by wrapping all plain intents into a effect that will pass on the errors
