### ISSUE TITLE
Add a LICENSE file.

### ISSUE THREAD

**Issue by tomprince** [python-effect/effect#38]
The `setup.py` lists a license, but it would be good to include it explicitly as a file.

**Comment by radix** [comment]
@tomprince the license is actually at the bottom of the README file. Do you think it's important for there to be a separate file containing the license text?

**Comment by tomprince** [comment]
It probably doesn't matter. `LICENSE` or `COPYING` is where *I* would expect to find things, but as long as it is included, it doesn't matter.

**Comment by radix** [comment]
okay, cool.
