### ISSUE TITLE
SequenceDispatcher incompatible with @do

### ISSUE THREAD

**Issue by rbtcollins** [python-effect/effect#64]
@do creates a function on the fly which we then can't use to match the intent in test code:

```
@do
def program():
    name = yield Effect(Print('What... is your quest?'))
...
    def test_print(self):
        def check_message(print_):
            self.assertEqual(["What... is your quest?"], print_.line)

        sequence = SequenceDispatcher([
            (Func(None), None),
            (Print('What... is your quest?'), check_message),
            ])

        with sequence.consume():
            sync_perform(sequence, program())
```

fails:

```
======================================================================
ERROR: 06.Tests.test_print
----------------------------------------------------------------------
Traceback (most recent call last):
  File "06.py", line 80, in test_print
    sync_perform(sequence, program())
  File "/home/robertc/.virtualenvs/effect/local/lib/python2.7/site-packages/effect/_sync.py", line 34, in sync_perform
    six.reraise(*errors[0])
  File "/home/robertc/.virtualenvs/effect/local/lib/python2.7/site-packages/effect/_base.py", line 154, in _perform
    raise NoPerformerFoundError(effect.intent)
effect._base.NoPerformerFoundError: Func(func=<function doit at 0x7f09c143b5f0>)
```

Pulling out the func is hard because of their being no dispatcher for perform_func

**Comment by radix** [comment]
You can use `with sequence.consume()` and perform with a dispatcher, so:

```python
with sequence.consume():
    sync_perform(ComposedDispatcher([sequence, base_dispatcher]), program())
```

This is what we do in Otter. I'm also planning on moving some more utility functions into effect to make this more concise:

- perform_sequence: https://github.com/rackerlabs/otter/blob/ce29eccb67ffc1d137bb50a2cb8f63e4ad3c11c6/otter/test/utils.py#L770
- nested_parallel: https://github.com/rackerlabs/otter/blob/ce29eccb67ffc1d137bb50a2cb8f63e4ad3c11c6/otter/test/utils.py#L822
- nested_sequence (pretty obscure, but very useful when you need it): https://github.com/rackerlabs/otter/blob/ce29eccb67ffc1d137bb50a2cb8f63e4ad3c11c6/otter/test/utils.py#L787

**Comment by radix** [comment]
Closing; if you have any more problems with this please let me know. #69 ameliorates this problem btw.
