### ISSUE TITLE
automate wrapping into effects via helpers or builtin primitives

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-effect/effect#67]
when working with sequences to express flows,
i commonly find myself wrapping plain intent objects into effects

for sequences and performers alike, i'd like to get tools that help with the mapping

i currently use the following code in the project

also please scrutinize the current usage by me,
i'm aware that its having some weaknesses since it fits the project

```python
import six
from effect import Effect
from effect.fold import FoldError, sequence

def pass_interupts(error):
    original = error
    if error[0] is not FoldError:
        six.reraise(*error)
    while error[0] is FoldError:
        error = error[1].wrapped_exception
    if error[0] in (SystemExit, KeyboardInterrupt):
        six.reraise(*error)
    else:
        six.reraise(*original)

def intent_sequence(intents):
    effects = [
        Effect(x) if not isinstance(x, Effect) else x
        for x in intents]
    return sequence(effects).on(error=pass_interupts)
```

**Comment by radix** [comment]
I'm not sure exactly what you're suggesting. Are you proposing that the `intent_sequence` function be added to Effect?

**Comment by RonnyPfannschmidt** [comment]
its just an example of a crude helper that helped me in a project - i'd like to see soem general convenience tools

**Comment by radix** [comment]
Okay. Well I can't think of any general way to improve this code yet; it's kind of related to #37, which I've pretty much given up on, but if you have any more specific suggestions then please feel free to create more tickets.

In your case I would recommend wrapping Effect around the intents wherever you're creating them; that way everything has a uniform API and anyone can attach callbacks or whatever if they need to.
