### ISSUE TITLE
sync_perfomer's inner sync_wrapper disallows keyword arguments

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-effect/effect#68]

**Comment by radix** [comment]
Can you explain the problem a bit more? The returned function must conform to the interface expected of performers returned from dispatchers: it accepts positional arguments for dispatcher, intent, and box.

**Comment by RonnyPfannschmidt** [comment]
it breaks for something like

```
@sync_performer
def myfunc(dispatcher. intent, extra=None):
  ...

dispatcher = TypeDispatcher(
  MyType: partial(myfunc, extra=42),
)

**Comment by radix** [comment]
Thanks @RonnyPfannschmidt :)
