### ISSUE TITLE
Tests fail on python3.7

### ISSUE THREAD

**Issue by marsam** [python-effect/effect#78]
SInce `async` is a reserved keyword since python 3.7, the tests fails on `from .async import ...` with `SyntaxError`
https://github.com/python-effect/effect/blob/9946975141af6220ed647baf2ca2367fe9152aaf/effect/test_intents.py#L24
https://github.com/python-effect/effect/blob/9946975141af6220ed647baf2ca2367fe9152aaf/effect/test_intents.py#L24

**Comment by radix** [comment]
Thanks for the report @marsam! I'll try to take a look at it this weekend. If you have any suggestions for how to maintain backwards compatibility while also supporting 3.7 in this case, I would love to hear them!

**Comment by radix** [comment]
version 0.12.0 is now released with python 3.7 support.

**Comment by marsam** [comment]
Thanks!
