### ISSUE TITLE
naming: success/failure vs success/error

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [python-effect/effect#80]
1. it seems that `success/failure`:

```
    effect.on(
        success=lambda value: print("I like {} too!".format(value)),
        failure=lambda error: print("sorry, there was an error. {}".format(error))
    )
```

2. reads better then `success/error`:

```
    effect.on(
        success=lambda result: print("I like {} too!".format(result)),
        error=lambda e: print("sorry, there was an error. {}".format(e))
    )
```

:smile:

**Comment by radix** [comment]
Hi @Andrei-Pozolotin! I appreciate that you want to improve Effect, but I don't think that "failure" is so much better than "error" that it is worth complicating the API by either making a backwards-incompatible change, or by supporting multiple keywords to mean the same thing.

Thank you for filing a ticket with your suggestion, though!
